# Generated by Django 3.2.7 on 2021-10-20 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Performance', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200)),
                ('Name', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='good.portfolio')),
            ],
        ),
    ]
